### ISSUE TITLE
移植问题：这一行使用 sysv64 ABI，我该怎样从aarch64 assembly 跳入main.rs: entry中？

### ISSUE THREAD

**Issue by Jerryy959** [rcore-os/RVM1.5#2]
https://github.com/rcore-os/RVM1.5/blob/d317825d748c6530144eaf5d758afa5c76c32232/src/main.rs#L144-L155

**Comment by equation314** [comment]
类似以下方法，在 `asm!` 宏中指定 `entry` 符号：
https://github.com/rcore-os/RVM1.5/blob/d317825d748c6530144eaf5d758afa5c76c32232/src/arch/x86_64/entry.rs#L13-L20

**Comment by Comet959** [comment]
> arch=x86_64的entry.rs中的switch_stack函数(下图)与main.rs中的entry函数(一楼)同样使用的是 extern "sysv64" ，但如果arch=aarch64，entry.rs应该使用extern "aarch64"，还能正常跳入main.rs吗？
> 
> https://github.com/rcore-os/RVM1.5/blob/d317825d748c6530144eaf5d758afa5c76c32232/src/arch/x86_64/entry.rs#L5-L30

我的意思是，不同架构的entry.rs函数中的asm abi不同，但是main函数中的abi是sysv64，想问下这里该怎么处理？
